### ISSUE TITLE
two small issues with the docker instructions

### ISSUE THREAD

**Issue by abate** [AJaySi/AI-Writer#190]
Hello devs :)

I encountered two minor problem in the Dockerfile instruction provided :  

- the first is easily fix: `docker build -t alwrity -f "Getting Started/Option_3_Docker_Install/Dockerfile" .` the path of the docker file changed

The second here, I was not able to solve it. I tried to change the base image ( upgrade to 3.12-slim ) and change the requirements.txt file, but I didn't manage.

Not sure what is wrong. There must be some requirements that keep pulling in the wrong version of panda-ta

```
ImportError: cannot import name 'NaN' from 'numpy' (/usr/local/lib/python3.12/site-packages/numpy/__init__.py)
Traceback:

File "/app/alwrity.py", line 81, in <module>
    from lib.utils.ui_setup import setup_ui, setup_alwrity_ui
File "/app/lib/utils/ui_setup.py", line 10, in <module>
    from lib.utils.alwrity_utils import ai_social_writer
File "/app/lib/utils/alwrity_utils.py", line 11, in <module>
    from lib.ai_writers.ai_finance_report_generator.ai_financial_dashboard import get_dashboard
File "/app/lib/ai_writers/ai_finance_report_generator/ai_financial_dashboard.py", line 22, in <module>
    from ...ai_web_researcher.finance_data_researcher import get_finance_data, get_fin_options_data
File "/app/lib/ai_web_researcher/finance_data_researcher.py", line 4, in <module>
    import pandas_ta as ta
File "/usr/local/lib/python3.12/site-packages/pandas_ta/__init__.py", line 116, in <module>
    from pandas_ta.core import *
File "/usr/local/lib/python3.12/site-packages/pandas_ta/core.py", line 18, in <module>
    from pandas_ta.momentum import *
File "/usr/local/lib/python3.12/site-packages/pandas_ta/momentum/__init__.py", line 34, in <module>
    from .squeeze_pro import squeeze_pro
File "/usr/local/lib/python3.12/site-packages/pandas_ta/momentum/squeeze_pro.py", line 2, in <module>
    from numpy import NaN as npNaN
```

It would also be great if you can also release the app as a docker image on dockerhub or similar services, and maybe
provide a ready to use docker-compose file for a quick local installation and testing.

regards

**Comment by uniqueumesh** [comment]
Hello @abate please give us some time to look into this issue. We will update you ASAP.

Regards

**Comment by AJaySi** [comment]
1. [requirements.txt] specifies:pandas-ta>=0.3.14b0
2. [numpy>=1.24.0]
3. The Dockerfile uses Python 3.12 for build, but Python 3.11-slim for runtime (this can cause subtle issues).
4. The error is due to an incompatibility between recent numpy versions (1.24+) and older pandas-ta versions, which try to import NaN from numpy (removed in numpy 1.24).

---
**Solution**:

Pin pandas-ta to a version compatible with numpy 1.24+ (e.g., pandas-ta>=0.3.14b0,!=0.3.14b0,>=0.3.15), or downgrade numpy to <1.24.
Also, use the same Python version in both build and runtime stages in Dockerfile.

---

requirements.txt: pandas-ta is now pinned to >=0.3.15 for compatibility with numpy >=1.24.0.
Dockerfile: Both build and runtime stages now use Python 3.12 for consistency.
docker-compose.yml: Added for easy local installation and testing. You can now run the app with:
```
cd "Getting Started/Option_3_Docker_Install"
docker-compose up --build
```
For Docker Hub release, you can build and push the image with:
```
docker build -t yourdockerhubusername/alwrity:latest -f "Getting Started/Option_3_Docker_Install/Dockerfile" .
docker push yourdockerhubusername/alwrity:latest
```

**Comment by uniqueumesh** [comment]
@AJaySi Thank you for your support. I'll test and update you. 

@abate please let us know if your issue is solved now.

Regards

**Comment by MRobi1** [comment]
> docker-compose.yml: Added for easy local installation and testing. You can now run the app with:
> 
> ```
> cd "Getting Started/Option_3_Docker_Install"
> docker-compose up --build
> ```

Getting an error on the pandas-ta version using this method.

```
#12 15.10   Downloading yfinance-0.2.63-py2.py3-none-any.whl.metadata (5.8 kB)
#12 15.14 ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
#12 15.14 ERROR: Could not find a version that satisfies the requirement pandas-ta>=0.3.15 (from versions: 0.3.14b0)
#12 15.29 ERROR: No matching distribution found for pandas-ta>=0.3.15
#12 ERROR: process "/bin/sh -c pip install --upgrade pip &&     pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [alwrity runtime  8/10] RUN pip install --upgrade pip &&     pip install --no-cache-dir -r requirements.txt:
14.89   Downloading lxml_html_clean-0.4.2-py3-none-any.whl.metadata (2.4 kB)
14.95 Collecting streamlit>=1.44.0 (from -r requirements.txt (line 44))
14.97   Downloading streamlit-1.46.0-py3-none-any.whl.metadata (9.0 kB)
15.00 Collecting Authlib>=1.3.2 (from -r requirements.txt (line 45))
15.03   Downloading authlib-1.6.0-py2.py3-none-any.whl.metadata (4.1 kB)
15.08 Collecting yfinance>=0.2.36 (from -r requirements.txt (line 46))
15.10   Downloading yfinance-0.2.63-py2.py3-none-any.whl.metadata (5.8 kB)
15.14 ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
15.14 ERROR: Could not find a version that satisfies the requirement pandas-ta>=0.3.15 (from versions: 0.3.14b0)
15.29 ERROR: No matching distribution found for pandas-ta>=0.3.15
```

**Comment by MRobi1** [comment]
Changing requirements.txt back to pandas-ta>=0.3.14b0 allows the installation to complete.
However when browsing to http://IPADDR:8501 I get presented with

```
FileNotFoundError: [Errno 2] No such file or directory: 'lib/workspace/alwrity_ui_styling.css'
Traceback:
File "/app/alwrity.py", line 30, in <module>
    with open('lib/workspace/alwrity_ui_styling.css', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm assuming unrelated to pandas-ta

**Comment by rstraszewski** [comment]
> > docker-compose.yml: Added for easy local installation and testing. You can now run the app with:
> > ```
> > cd "Getting Started/Option_3_Docker_Install"
> > docker-compose up --build
> > ```
> 
> Getting an error on the pandas-ta version using this method.
> 
> ```
> #12 15.10   Downloading yfinance-0.2.63-py2.py3-none-any.whl.metadata (5.8 kB)
> #12 15.14 ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
> #12 15.14 ERROR: Could not find a version that satisfies the requirement pandas-ta>=0.3.15 (from versions: 0.3.14b0)
> #12 15.29 ERROR: No matching distribution found for pandas-ta>=0.3.15
> #12 ERROR: process "/bin/sh -c pip install --upgrade pip &&     pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
> ------
>  > [alwrity runtime  8/10] RUN pip install --upgrade pip &&     pip install --no-cache-dir -r requirements.txt:
> 14.89   Downloading lxml_html_clean-0.4.2-py3-none-any.whl.metadata (2.4 kB)
> 14.95 Collecting streamlit>=1.44.0 (from -r requirements.txt (line 44))
> 14.97   Downloading streamlit-1.46.0-py3-none-any.whl.metadata (9.0 kB)
> 15.00 Collecting Authlib>=1.3.2 (from -r requirements.txt (line 45))
> 15.03   Downloading authlib-1.6.0-py2.py3-none-any.whl.metadata (4.1 kB)
> 15.08 Collecting yfinance>=0.2.36 (from -r requirements.txt (line 46))
> 15.10   Downloading yfinance-0.2.63-py2.py3-none-any.whl.metadata (5.8 kB)
> 15.14 ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
> 15.14 ERROR: Could not find a version that satisfies the requirement pandas-ta>=0.3.15 (from versions: 0.3.14b0)
> 15.29 ERROR: No matching distribution found for pandas-ta>=0.3.15
> ```

I have the same error.

**Comment by AJaySi** [comment]
Hello all, 
I will fix and update the code today. It between features and also Travelling, hence limited connectivity. 
It should be fixed today. Thank you for your patience.

Regards.

**Comment by meshwara** [comment]
Any update for this problem ?

**Comment by uniqueumesh** [comment]
@meshwara @rstraszewski @MrSnoozles @abate 

Please give @AJaySi some time to fix this issue. You can also [follow these steps](https://www.alwrity.com/post/getting-started-with-alwrity-ai-writer) to install ALwrity locally.

**Comment by caticodev** [comment]
`ImportError: cannot import name 'NaN' from 'numpy'`

The error persists on MacOS. However, the fix from https://github.com/AJaySi/AI-Writer/issues/157 works for me.
